/* inc/config_flopcpp.h.  Generated by configure.  */
/* inc/config_flopcpp.h.in.  Generated from configure.ac by autoheader.  */

/* Define to the name of the default solver to be used in CBC in small letters
   */
#define CBC_DEFAULT_SOLVER "clp"

/* Define to the debug sanity check level (0 is no test) */
#define COIN_FLOPCPP_CHECKLEVEL 0

/* Define to the debug verbosity level (0 is no output) */
#define COIN_FLOPCPP_VERBOSITY 0

/* Define to 1 if the Cbc package is used */
#define COIN_HAS_CBC 1

/* Define to 1 if the Cgl package is used */
#define COIN_HAS_CGL 1

/* Define to 1 if the Clp package is used */
#define COIN_HAS_CLP 1

/* Define to 1 if the CoinUtils package is used */
#define COIN_HAS_COINUTILS 1

/* Define to 1 if the Cplex package is available */
/* #undef COIN_HAS_CPX */

/* Define to 1 if the DyLP package is used */
#define COIN_HAS_DYLP 1

/* Define to 1 if the FlopCPP package is used */
#define COIN_HAS_FLOPCPP 1

/* Define to 1 if the FortMP package is available */
/* #undef COIN_HAS_FMP */

/* Define to 1 if Glpk package is available */
#define COIN_HAS_GLPK 1

/* Define to 1 if the Mosek package is available */
/* #undef COIN_HAS_MSK */

/* Define to 1 if the Osi package is used */
#define COIN_HAS_OSI 1

/* Define to 1 if the Osl package is available */
/* #undef COIN_HAS_OSL */

/* Define to 1 if the Soplex package is available */
/* #undef COIN_HAS_SPX */

/* Define to 1 if the Sym package is used */
/* #undef COIN_HAS_SYM */

/* Define to 1 if the Xpress package is available */
/* #undef COIN_HAS_XPR */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "flopcpp"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "flopcpp@list.coin-or.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "FlopCpp"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "FlopCpp 1.0.6"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "flopcpp"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.0.6"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.0.6"
