/* inc/config_bonmin.h.  Generated by configure.  */
/* inc/config_bonmin.h.in.  Generated from configure.ac by autoheader.  */

/* Define to the debug sanity check level (0 is no test) */
#define COIN_BONMIN_CHECKLEVEL 0

/* Define to the debug verbosity level (0 is no output) */
#define COIN_BONMIN_VERBOSITY 0

/* If defined, the Ampl Solver Library is available. */
/* #undef COIN_HAS_ASL */

/* Define to 1 if the Bcp package is used */
#define COIN_HAS_BCP 1

/* Define to 1 if the Cbc package is used */
#define COIN_HAS_CBC 1

/* Define to 1 if the Cgl package is used */
#define COIN_HAS_CGL 1

/* Define to 1 if the Clp package is used */
#define COIN_HAS_CLP 1

/* Define to 1 if the CoinUtils package is used */
#define COIN_HAS_COINUTILS 1

/* Define to 1 if the Couenne package is used */
#define COIN_HAS_COUENNE 1

/* Define to 1 if the Cplex package is available */
/* #undef COIN_HAS_CPX */

/* Define to 1 if the DyLP package is used */
#define COIN_HAS_DYLP 1

/* Define to 1 if FilterSQP is available */
/* #undef COIN_HAS_FILTERSQP */

/* Define to 1 if the FortMP package is available */
/* #undef COIN_HAS_FMP */

/* Define to 1 if Glpk package is available */
#define COIN_HAS_GLPK 1

/* Define to 1 if the Ipopt package is used */
#define COIN_HAS_IPOPT 1

/* Define to 1 if the Mosek package is available */
/* #undef COIN_HAS_MSK */

/* Define to 1 if the Osi package is used */
#define COIN_HAS_OSI 1

/* Define to 1 if the Osl package is available */
/* #undef COIN_HAS_OSL */

/* Define to 1 if the Soplex package is available */
/* #undef COIN_HAS_SPX */

/* Define to 1 if the Sym package is used */
/* #undef COIN_HAS_SYM */

/* Define to 1 if the Vol package is used */
#define COIN_HAS_VOL 1

/* Define to 1 if the Xpress package is available */
/* #undef COIN_HAS_XPR */

/* Define to dummy `main' function (if any) required to link to the Fortran
   libraries. */
/* #undef F77_DUMMY_MAIN */

/* Define to a macro mangling the given C identifier (in lower and upper
   case), which must not contain underscores, for linking with Fortran. */
#define F77_FUNC(name,NAME) name ## _

/* As F77_FUNC, but for C identifiers containing underscores. */
#define F77_FUNC_(name,NAME) name ## _

/* Define if F77 and FC dummy `main' functions are identical. */
/* #undef FC_DUMMY_MAIN_EQ_F77 */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "bonmin"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "coin-bonmin@list.coin-or.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Bonmin"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Bonmin 1.1.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "bonmin"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.1.2"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.1.2"
