/* inc/config_bcp.h.  Generated by configure.  */
/* inc/config_bcp.h.in.  Generated from configure.ac by autoheader.  */

/* Define to the debug sanity check level (0 is no test) */
#define COIN_BCP_CHECKLEVEL 0

/* Define to the debug verbosity level (0 is no output) */
#define COIN_BCP_VERBOSITY 0

/* Define to 1 if the Bcp package is used */
#define COIN_HAS_BCP 1

/* Define to 1 if the Cgl package is used */
#define COIN_HAS_CGL 1

/* Define to 1 if the Clp package is used */
#define COIN_HAS_CLP 1

/* Define to 1 if the CoinUtils package is used */
#define COIN_HAS_COINUTILS 1

/* Define to 1 if the Mpi package is available */
/* #undef COIN_HAS_MPI */

/* Define to 1 if the Osi package is used */
#define COIN_HAS_OSI 1

/* Define to 1 if the Vol package is used */
#define COIN_HAS_VOL 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the `gethostname' function. */
#define HAVE_GETHOSTNAME 1

/* Define to 1 if you have the `getpid' function. */
#define HAVE_GETPID 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `mallinfo' function. */
#define HAVE_MALLINFO 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <process.h> header file. */
/* #undef HAVE_PROCESS_H */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if sysinfo function exists and runs with Bcp code */
/* #undef HAVE_SYSINFO */

/* Define to 1 if you have the <sys/resource.h> header file. */
#define HAVE_SYS_RESOURCE_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/sysinfo.h> header file. */
#define HAVE_SYS_SYSINFO_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "bcp"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "https://projects.coin-or.org/Bcp/newticket"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Bcp"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Bcp 1.2.3"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "bcp"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.2.3"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.2.3"
