/* inc/config_couenne.h.  Generated by configure.  */
/* inc/config_couenne.h.in.  Generated from configure.ac by autoheader.  */

/* Define to the debug sanity check level (0 is no test) */
#define COIN_COUENNE_CHECKLEVEL 0

/* Define to the debug verbosity level (0 is no output) */
#define COIN_COUENNE_VERBOSITY 0

/* If defined, the Ampl Solver Library is available. */
/* #undef COIN_HAS_ASL */

/* Define to 1 if the Bonmin package is used */
#define COIN_HAS_BONMIN 1

/* Define to 1 if the Cbc package is used */
#define COIN_HAS_CBC 1

/* Define to 1 if the Cgl package is used */
#define COIN_HAS_CGL 1

/* Define to 1 if the Clp package is used */
#define COIN_HAS_CLP 1

/* Define to 1 if the CoinUtils package is used */
#define COIN_HAS_COINUTILS 1

/* Define to 1 if the Couenne package is used */
#define COIN_HAS_COUENNE 1

/* Define to 1 if the Cplex package is available */
/* #undef COIN_HAS_CPX */

/* Define to 1 if the Ipopt package is used */
#define COIN_HAS_IPOPT 1

/* Define to 1 if the Osi package is used */
#define COIN_HAS_OSI 1

/* Define to 1 if the ThirdParty package is used */
#define COIN_HAS_THIRDPARTY 1

/* Define to 1 if you have the <cstdint> header file. */
/* #undef HAVE_CSTDINT */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "couenne"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "belotti@lehigh.edu"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Couenne"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Couenne 0.2.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "couenne"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.2.2"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.2.2"
