/* inc/config_os.h.  Generated by configure.  */
/* inc/config_os.h.in.  Generated from configure.ac by autoheader.  */

/* If defined, the Ampl Solver Library is available. */
/* #undef COIN_HAS_ASL */

/* Define to 1 if the Bcp package is used */
#define COIN_HAS_BCP 1

/* Define to 1 if the Bonmin package is used */
#define COIN_HAS_BONMIN 1

/* Define to 1 if the Cbc package is used */
#define COIN_HAS_CBC 1

/* Define to 1 if the Cgl package is used */
#define COIN_HAS_CGL 1

/* Define to 1 if the Clp package is used */
#define COIN_HAS_CLP 1

/* Define to 1 if the CoinUtils package is used */
#define COIN_HAS_COINUTILS 1

/* Define to 1 if the Couenne package is used */
#define COIN_HAS_COUENNE 1

/* Define to 1 if the cppad package is used */
#define COIN_HAS_CPPAD 1

/* Define to 1 if the Cplex package is available */
/* #undef COIN_HAS_CPX */

/* Define to 1 if the DyLP package is used */
#define COIN_HAS_DYLP 1

/* Define to 1 if Glpk package is available */
#define COIN_HAS_GLPK 1

/* Define to 1 if the Ipopt package is used */
#define COIN_HAS_IPOPT 1

/* Define to 1 if the Knitro package is available */
/* #undef COIN_HAS_KNITRO */

/* Define to 1 if the Lindo package is available */
/* #undef COIN_HAS_LINDO */

/* Define to 1 if the OS package is used */
#define COIN_HAS_OS 1

/* Define to 1 if the Osi package is used */
#define COIN_HAS_OSI 1

/* Define to 1 if the SYMPHONY package is used */
/* #undef COIN_HAS_SYMPHONY */

/* Define to 1 if the Vol package is used */
#define COIN_HAS_VOL 1

/* Define to the debug sanity check level (0 is no test) */
#define COIN_OS_CHECKLEVEL 0

/* Define to the debug verbosity level (0 is no output) */
#define COIN_OS_VERBOSITY 0

/* Define to dummy `main' function (if any) required to link to the Fortran
   libraries. */
/* #undef F77_DUMMY_MAIN */

/* Define to a macro mangling the given C identifier (in lower and upper
   case), which must not contain underscores, for linking with Fortran. */
#define F77_FUNC(name,NAME) name ## _

/* As F77_FUNC, but for C identifiers containing underscores. */
#define F77_FUNC_(name,NAME) name ## _

/* Define if F77 and FC dummy `main' functions are identical. */
/* #undef FC_DUMMY_MAIN_EQ_F77 */

/* Define to 1 if you have the <assert.h> header file. */
/* #undef HAVE_ASSERT_H */

/* Define to 1 if you have the <cassert> header file. */
#define HAVE_CASSERT 1

/* Define to 1 if you have the <cctype> header file. */
#define HAVE_CCTYPE 1

/* Define to 1 if you have the <cfloat> header file. */
#define HAVE_CFLOAT 1

/* Define to 1 if you have the <cieeefp> header file. */
/* #undef HAVE_CIEEEFP */

/* Define to 1 if you have the <cmath> header file. */
#define HAVE_CMATH 1

/* Define to 1 if you have the <cstdarg> header file. */
#define HAVE_CSTDARG 1

/* Define to 1 if you have the <cstdio> header file. */
#define HAVE_CSTDIO 1

/* Define to 1 if you have the <cstdlib> header file. */
#define HAVE_CSTDLIB 1

/* Define to 1 if you have the <cstring> header file. */
#define HAVE_CSTRING 1

/* Define to 1 if you have the <ctime> header file. */
#define HAVE_CTIME 1

/* Define to 1 if you have the <ctype.h> header file. */
/* #undef HAVE_CTYPE_H */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <float.h> header file. */
/* #undef HAVE_FLOAT_H */

/* Define to 1 if you have the <ieeefp.h> header file. */
/* #undef HAVE_IEEEFP_H */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <math.h> header file. */
/* #undef HAVE_MATH_H */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdarg.h> header file. */
/* #undef HAVE_STDARG_H */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
/* #undef HAVE_STDIO_H */

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <time.h> header file. */
/* #undef HAVE_TIME_H */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <winsock.h> header file. */
/* #undef HAVE_WINSOCK_H */

/* use if OS is MACOSX */
/* #undef MACOSX_ */

/* Define to be the name of C-function for NaN check */
#define MY_C_ISNAN isnan

/* use if OS is Cygwin */
/* #undef NOMINMAX */

/* Define the path to the OS root */
#define OSROOT_DIR "/home/cduquesne/CoinAll-1.3.1/OS"

/* Name of package */
#define PACKAGE "os"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "coin-os@list.coin-or.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "OS"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "OS 2.0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "os"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.0.1"

/* The size of a `double', as computed by sizeof. */
#define SIZEOF_DOUBLE 8

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 8

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* use to get lossless IO */
#define USE_DTOA 1

/* use if OS is Cygwin and complier is gnu */
/* #undef USE_OLD_UNISTD */

/* Version number of package */
#define VERSION "2.0.1"

/* use if OS is Windows */
/* #undef WIN_ */

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* use if XLC is the compiler */
/* #undef XLC_ */
